[workspace]
members = [
  "huff_lexer",
  "huff_utils",
  "huff_cli",
]
exclude = [ "assets", "huffup", "huff-examples" ]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
debug = true
